plugins {
    id 'java'
    id 'net.neoforged.moddev' version '2.0.147'
}

group = 'com.dsh.cyberware'
version = '0.3.8-Beta-Hotfix-1'
description = 'Cyberware - 赛博朋克风格义体植入系统'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

neoForge {
    version = '26.1.2.109'

    runs {
        client {
            client()
        }
        server {
            server()
        }
    }

    mods {
        cyberware {
            sourceSet sourceSets.main
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
